kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: falcon-sensor-sa-clusterrolebinding
  namespace: falcon-sensor
subjects:
  - kind: ServiceAccount
    name: falcon-sensor-sa
    namespace: falcon-sensor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: falcon-sensor-scc-privileged
