kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: falcon-sensor-sa-rolebinding
  namespace: falcon-sensor
subjects:
  - kind: ServiceAccount
    name: falcon-sensor-sa
    namespace: falcon-sensor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: falcon-sensor-scc-privileged